name = "spinogambinocasino-bet-net"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinocasino-bet.net"
HMAC_KEY = "903e444c36d943575ace5025b699ab1e829a5ab499ed8522cdc7f544ee2ad2c0"
COOKIE_NAME = "fqe"
PLAY_PATH = "start-now"
BUTTON_ID = "p556f7c9ad8e3607876022dc220225f77"
GATE_SALT = "fae16d92cc93bf3a"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "jv2w"
CTA_SELECTOR = ".play-button"
