name = "spinogambinocasino-bet-net"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinocasino-bet.net"
HMAC_KEY = "903e444c36d943575ace5025b699ab1e829a5ab499ed8522cdc7f544ee2ad2c0"
COOKIE_NAME = "88s"
PLAY_PATH = "explore"
BUTTON_ID = "p556f7c9ad8e3607876022dc220225f77"
GATE_SALT = "bcbe9cf8b1175005"
